#!/usr/bin/env bash

# example of firefox
# x11 / xfce

set -euo pipefail
(exec bwrap \
	--ro-bind /usr /usr \
	--dir /tmp \
	--symlink ../tmp var/tmp \
	--proc /proc \
	--dev /dev \
	--dev-bind /dev/snd /dev/snd \
	--ro-bind /tmp/.X11-unix /tmp/.X11-unix \
	--ro-bind /etc/hostname /etc/hostname \
	--ro-bind /etc/hosts /etc/hosts \
	--ro-bind /etc/localtime /etc/localtime \
	--ro-bind /etc/nsswitch.conf /etc/nsswitch.conf \
	--ro-bind /etc/resolv.conf /etc/resolv.conf \
	--ro-bind /etc/xdg /etc/xdg \
	--ro-bind /etc/gtk-2.0 /etc/gtk-2.0 \
	--ro-bind /etc/gtk-3.0 /etc/gtk-3.0 \
	--ro-bind /etc/fonts /etc/fonts \
	--ro-bind /etc/mime.types /etc/mime.types \
	--symlink usr/lib /lib \
	--symlink usr/lib64 /lib64 \
	--symlink usr/bin /bin \
	--symlink usr/sbin /sbin \
	--tmpfs /run \
	--bind ~/.mozilla ~/.mozilla \
	--bind ~/.cache/mozilla ~/.cache/mozilla \
	--bind ~/Downloads ~/Downloads \
	--chdir / \
	--dir /var \
	--file 11 /etc/passwd \
	--file 12 /etc/group \
	--unshare-user-try \
	--unshare-pid \
	--unshare-uts \
	--unshare-cgroup-try \
	--new-session \
	--seccomp 10 \
	/usr/bin/firefox) \
	\
	10< /usr/local/bin/seccomp_default_filter.bpf \
	11< <(getent passwd $UID 65534) \
	12< <(getent group $(id -g) 65534)
